<a href="https://colab.research.google.com/github/Muntasir2179/pytorch-learnig/blob/tensors/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Libraries

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


# Pytorch Tensors

In [6]:
# scalar
scaler = torch.tensor([[1,2,3],[4,5,6]])
scaler, scaler.ndim, scaler.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 2,
 torch.Size([2, 3]))

In [11]:
# let's create a matrix
matrix = torch.tensor([[7, 8, 9],
                       [9, 10, 11],
                       [1, 2, 3]])
matrix.ndim, matrix.shape

(2, torch.Size([3, 3]))

In [13]:
matrix[0], matrix[1], matrix[2]

(tensor([7, 8, 9]), tensor([ 9, 10, 11]), tensor([1, 2, 3]))

In [14]:
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
tensor.ndim, tensor.shape

(3, torch.Size([1, 3, 3]))

## Random Tensors

Random tensors are imoprtant because the way many neural networks learn in that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`start with random numbers -> look at data -> undate random numbers -> look at data -> update random numbers`

In [24]:
# creating a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5738, 0.5508, 0.5802, 0.9005],
        [0.6677, 0.9463, 0.6852, 0.5003],
        [0.2033, 0.5830, 0.8357, 0.6116]])

In [27]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Tensor with zeros and ones

In [28]:
zero_tesnor = torch.zeros(size=(3, 2))
zero_tesnor

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [29]:
ones_tensor = torch.ones(size=(3, 4))
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
ones_tensor.dtype

torch.float32

## Range of tensors and tensors-like

In [34]:
# use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Data Types

**NOTE:** Tensor datatypes is one of the three big errors we will find while run into with PyTorch and Deep Learning.

1. Tensors not right datatypes.
2. Tensors not right shape.
3. Tenosrs not on right device.

In [40]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # what data type is tensor (float16, float32, float64, int16, int32, int64)
                               device=None,        # what device is the tensor on
                               requires_grad=False)  # whether or not to track gradients with this tensor operaitons
float_32_tensor

tensor([3., 6., 9.])

In [41]:
float_32_tensor.dtype

torch.float32

In [43]:
# changing the tensor datatype
converted_float_16 = float_32_tensor.type(torch.float16)
converted_float_16

tensor([3., 6., 9.], dtype=torch.float16)