<a href="https://colab.research.google.com/github/Muntasir2179/pytorch-learnig/blob/tensors/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Libraries

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


# Pytorch Tensors

In [2]:
# scalar
scaler = torch.tensor([[1,2,3],[4,5,6]])
scaler, scaler.ndim, scaler.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 2,
 torch.Size([2, 3]))

In [3]:
# let's create a matrix
matrix = torch.tensor([[7, 8, 9],
                       [9, 10, 11],
                       [1, 2, 3]])
matrix.ndim, matrix.shape

(2, torch.Size([3, 3]))

In [4]:
matrix[0], matrix[1], matrix[2]

(tensor([7, 8, 9]), tensor([ 9, 10, 11]), tensor([1, 2, 3]))

In [5]:
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [6]:
tensor.ndim, tensor.shape

(3, torch.Size([1, 3, 3]))

## Random Tensors

Random tensors are imoprtant because the way many neural networks learn in that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`start with random numbers -> look at data -> undate random numbers -> look at data -> update random numbers`

In [7]:
# creating a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6789, 0.2049, 0.5268, 0.4010],
        [0.4646, 0.5541, 0.9215, 0.4181],
        [0.8643, 0.4510, 0.5765, 0.2861]])

In [8]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Tensor with zeros and ones

In [9]:
zero_tesnor = torch.zeros(size=(3, 2))
zero_tesnor

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [10]:
ones_tensor = torch.ones(size=(3, 4))
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
ones_tensor.dtype

torch.float32

## Range of tensors and tensors-like

In [12]:
# use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Data Types

**NOTE:** Tensor datatypes is one of the three big errors we will find while run into with PyTorch and Deep Learning.

1. Tensors not right datatypes.
2. Tensors not right shape.
3. Tenosrs not on right device.

In [14]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # what data type is tensor (float16, float32, float64, int16, int32, int64)
                               device=None,        # what device is the tensor on
                               requires_grad=False)  # whether or not to track gradients with this tensor operaitons
float_32_tensor

tensor([3., 6., 9.])

In [15]:
float_32_tensor.dtype

torch.float32

In [16]:
# changing the tensor datatype
converted_float_16 = float_32_tensor.type(torch.float16)
converted_float_16

tensor([3., 6., 9.], dtype=torch.float16)

## Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensor not right shape - to get shape from a tensor, we can use `tensor.shape`
3. Tensor not on the right device - to get device from a tensor, can use `tensor.device`

In [17]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5802, 0.4348, 0.4966, 0.4241],
        [0.7445, 0.9075, 0.2459, 0.9402],
        [0.8664, 0.2582, 0.9386, 0.9101]])

In [18]:
# find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5802, 0.4348, 0.4966, 0.4241],
        [0.7445, 0.9075, 0.2459, 0.9402],
        [0.8664, 0.2582, 0.9386, 0.9101]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


## Mathemetical operations with tensor

Tensor operations include:

* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [19]:
# addition of tensor
tensor_1 = torch.tensor([1, 2, 3])
tensor_2 = torch.tensor([4, 5, 6])
tensor_1 + tensor_2, torch.add(tensor_1, tensor_2)

(tensor([5, 7, 9]), tensor([5, 7, 9]))

In [20]:
# subtraction with tensor
tensor_1 - tensor_2, torch.subtract(tensor_1, tensor_2), torch.sub(tensor_1, tensor_2)

(tensor([-3, -3, -3]), tensor([-3, -3, -3]), tensor([-3, -3, -3]))

In [21]:
# multiplication with tensor
tensor_1 * tensor_2, torch.mul(tensor_1, tensor_2), torch.multiply(tensor_1, tensor_2)

(tensor([ 4, 10, 18]), tensor([ 4, 10, 18]), tensor([ 4, 10, 18]))

In [22]:
# division with tensor
tensor_2 / tensor_1, torch.div(tensor_2, tensor_1), torch.divide(tensor_2, tensor_1)

(tensor([4.0000, 2.5000, 2.0000]),
 tensor([4.0000, 2.5000, 2.0000]),
 tensor([4.0000, 2.5000, 2.0000]))

## Matrix multiplication

1. Element wise multiplication.
2. Matrix multiplication.

In [23]:
# matrix multiplication
matrix_1 = torch.tensor([[1, 2, 3],
                         [2, 3, 4],
                         [3, 4, 5]])
matrix_2 = torch.tensor([1, 2, 3])

torch.matmul(matrix_1, matrix_2)

tensor([14, 20, 26])

In [24]:
# element wise multiplication
tensor_1 = torch.tensor([1, 2, 3])
tensor_2 = torch.tensor([4, 5, 6])

print(tensor_1, " * ", tensor_2)
print(f"Equals: {tensor_1 * tensor_2}")

tensor([1, 2, 3])  *  tensor([4, 5, 6])
Equals: tensor([ 4, 10, 18])


## Time comparison of tensor operations

In [27]:
%%time
value = 0
for i in range(len(tensor_1)):
  value += tensor_1[i] * tensor_1[i]
print(value)

tensor(14)
CPU times: user 2.25 ms, sys: 0 ns, total: 2.25 ms
Wall time: 2.13 ms


In [28]:
%%time
torch.matmul(tensor_1, tensor_1)

CPU times: user 1.21 ms, sys: 32 µs, total: 1.24 ms
Wall time: 1.26 ms


tensor(14)